name: "terraform formatting"

on:
  push:
    branches:
      - master
  pull_request:
    
defaults:
  run:
    shell: bash
   
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform format - root
      id: fmt_root
      run: terraform fmt -check
    - name: Terraform format - lambda module
      id: fmt_lambda
      run: terraform fmt -check ./modules/lambda/
    - name: Terraform format - lambda module
      id: fmt_api_gateway
      run: terraform fmt -check ./modules/api_gateway/